
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    username: name
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format_sql: true